services:
    zikula_theme_module.twig.extension.theme_extension:
        class: Zikula\ThemeModule\Twig\Extension\ThemeExtension
        arguments:
            - "@zikula_theme_module.api.page_asset"
            - "@zikula_core.common.theme.asset_helper"
        tags:
            - { name: twig.extension }

    zikula_theme_module.twig.extension.page_var_extension:
        class: Zikula\ThemeModule\Twig\Extension\PageVarExtension
        arguments:
            - '@translator.default'
            - '@zikula_core.common.theme.pagevars'
        tags:
            - { name: twig.extension }
